export const REST_API_VERSION = "2026-03-10";

export const DAY_NAMES = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const languageGroups: Record<string, string[]> = {
  TypeScript: ["Frontend", "Backend"],
  JavaScript: ["Frontend", "Backend"],
  HTML: ["Frontend"],
  CSS: ["Frontend"],
  SCSS: ["Frontend"],
  Vue: ["Frontend"],
  Svelte: ["Frontend"],
  Python: ["Backend", "AI"],
  R: ["AI"],
  Jupyter: ["AI"],
  Go: ["Backend"],
  Rust: ["Backend"],
  Java: ["Backend"],
  C: ["Backend"],
  "C++": ["Backend"],
  "C#": ["Backend"],
  PHP: ["Backend"],
  Ruby: ["Backend"],
  Kotlin: ["Mobile"],
  Swift: ["Mobile"],
  Dart: ["Mobile"],
  Shell: ["DevOps"],
  Dockerfile: ["DevOps"],
  HCL: ["Cloud"],
  SQL: ["Database"],
};

export const topicGroups: Record<string, string> = {
  react: "Frontend",
  nextjs: "Frontend",
  next: "Frontend",
  tailwind: "Frontend",
  vue: "Frontend",
  svelte: "Frontend",
  node: "Backend",
  express: "Backend",
  fastapi: "Backend",
  django: "Backend",
  postgres: "Database",
  postgresql: "Database",
  mysql: "Database",
  mongodb: "Database",
  redis: "Database",
  aws: "Cloud",
  azure: "Cloud",
  gcp: "Cloud",
  cloudflare: "Cloud",
  docker: "DevOps",
  kubernetes: "DevOps",
  testing: "Testing",
  vitest: "Testing",
  jest: "Testing",
  playwright: "Testing",
  reactnative: "Mobile",
  flutter: "Mobile",
  ai: "AI",
  ml: "AI",
  llm: "AI",
};
